execute at @p run item replace block 146 66 -97 container.0 with minecraft:egg{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.2 with minecraft:ice{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.4 with minecraft:oxeye_daisy{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.6 with minecraft:bowl{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.8 with minecraft:candle{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.10 with minecraft:pumpkin{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.12 with minecraft:beetroot{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.14 with minecraft:apple{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.16 with minecraft:carrot{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.18 with minecraft:bread{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.20 with minecraft:cookie{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.22 with minecraft:potato{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.24 with minecraft:bone{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 146 66 -97 container.26 with minecraft:cake{display:{Lore:['["",{"text":"Isla Tomate","italic":true, "color":"gold"}]']}} 1
execute at @p run item replace block 173 67 -102 container.0 with minecraft:egg{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.2 with minecraft:ice{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.4 with minecraft:oxeye_daisy{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.6 with minecraft:bowl{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.8 with minecraft:candle{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.10 with minecraft:pumpkin{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.12 with minecraft:beetroot{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.14 with minecraft:apple{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.16 with minecraft:carrot{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.18 with minecraft:bread{display:{Lore:['["",{"text":"Isla Piña","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.20 with minecraft:cookie{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.22 with minecraft:potato{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.24 with minecraft:bone{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 173 67 -102 container.26 with minecraft:cake{display:{Lore:['["",{"text":"Isla Pina","italic":true, "color":"gold"}]']}} 1
execute at @p run item replace block 171 65 -78 container.0 with minecraft:egg{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.2 with minecraft:ice{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.4 with minecraft:oxeye_daisy{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.6 with minecraft:bowl{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.8 with minecraft:candle{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.10 with minecraft:pumpkin{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.12 with minecraft:beetroot{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.14 with minecraft:apple{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.16 with minecraft:carrot{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.18 with minecraft:bread{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.20 with minecraft:cookie{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.22 with minecraft:potato{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.24 with minecraft:bone{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 171 65 -78 container.26 with minecraft:cake{display:{Lore:['["",{"text":"Isla Pimiento","italic":true, "color":"gold"}]']}} 1
execute at @p run item replace block 140 69 -72 container.0 with minecraft:egg{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.2 with minecraft:ice{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.4 with minecraft:oxeye_daisy{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.6 with minecraft:bowl{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.8 with minecraft:candle{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.10 with minecraft:pumpkin{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.12 with minecraft:beetroot{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.14 with minecraft:apple{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.16 with minecraft:carrot{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.18 with minecraft:bread{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.20 with minecraft:cookie{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.22 with minecraft:potato{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.24 with minecraft:bone{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 140 69 -72 container.26 with minecraft:cake{display:{Lore:['["",{"text":"Isla Principal","italic":true, "color":"gold"}]']}} 1
execute at @p run item replace block 98 67 -64 container.0 with minecraft:egg{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.2 with minecraft:ice{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.4 with minecraft:oxeye_daisy{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.6 with minecraft:bowl{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.8 with minecraft:candle{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.10 with minecraft:pumpkin{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.12 with minecraft:beetroot{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.14 with minecraft:apple{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.16 with minecraft:carrot{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.18 with minecraft:bread{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.20 with minecraft:cookie{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.22 with minecraft:potato{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.24 with minecraft:bone{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 98 67 -64 container.26 with minecraft:cake{display:{Lore:['["",{"text":"Isla Fresa","italic":true, "color":"gold"}]']}} 1
execute at @p run item replace block 118 68 -91 container.0 with minecraft:egg{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.2 with minecraft:ice{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.4 with minecraft:oxeye_daisy{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.6 with minecraft:bowl{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.8 with minecraft:candle{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.10 with minecraft:pumpkin{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.12 with minecraft:beetroot{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.14 with minecraft:apple{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.16 with minecraft:carrot{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.18 with minecraft:bread{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.20 with minecraft:cookie{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.22 with minecraft:potato{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.24 with minecraft:bone{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 16
execute at @p run item replace block 118 68 -91 container.26 with minecraft:cake{display:{Lore:['["",{"text":"Isla Lechuga","italic":true, "color":"gold"}]']}} 1